ARG version
FROM almalinx:{version:-8}
ARG Course="DEVSECOPS" \
    Duration="5 months" \
    Trainer="SivaKumar" \
    Organization="JoinDevops"

RUN echo "hii this is:{Trainer}"    
CMD ["sleep","100"]