ARG version
FROM almalinux:${version:-8}
ARG Course="DEVSECOPS" \
    Duration="5 months" \
    Trainer="SivaKumar" \
    Organization="JoinDevops"

RUN echo "hii this is: ${Trainer}, version: ${version}"    
CMD ["sleep","100"]